### PR TITLE
add parameter i

### LINKED ISSUE #4: Parameter -i

### PR DESCRIPTION
**Pull request by justinmueller05082000**
fixes #4

### CODE REVIEW

**Review by Al2Klimov — COMMENTED** [review]
Why not just upper-casing everything as in sort?

**Comment by justinmueller05082000** [comment]
it makes no difference if upper or lower cast it

**Comment by Al2Klimov** [comment]
Sorry, I meant lower-case.

**Comment by justinmueller05082000** [comment]
well i do lower case everything?

**Comment by Al2Klimov** [comment]
But not the same way as in sort.

**Comment by justinmueller05082000** [comment]
but the same way as uniq

**Comment by Al2Klimov** [comment]
I meant in _your_ sort.

**Comment by justinmueller05082000** [comment]
in my sort I use bytes.ToUpper() but the normal sort as well as the normal uniq does not change the output. It does only change the comparators in the code but NOT the result that is printed. I added the ignore case parameter and its the same as the linux command uniq.

**Comment by Al2Klimov** [comment]
Your sort's -f **does** change the output. And wouldn't it be much simpler to change it here as well?

**Comment by justinmueller05082000** [comment]
Yeah MY sort does but the original one does not. It would be way more easy if it doesnt matter if the output is also in lower/upper case. I just tried to get the same result as uniq.

**Comment by Al2Klimov** [comment]
What for? I didn't require that for sort either.

**Comment by justinmueller05082000** [comment]
Sort was a while ago I didn't remember.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
* [x] `git reset --soft HEAD~$(git rev-list --count $(git merge-base HEAD master)..HEAD^)`
* [x] `git commit --amend --no-edit`
* [x] `git push -f origin feature/add-parameter-i-4`

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Write a test protocol.

**Comment by justinmueller05082000** [comment]
**Test protocol:**

**toUniq.txt:**

```
RAT
Rat
RAT
Dog
Dog
Cat
Esel
Esel
Esel
Hund
Hund
```

**Go code:**

**Terminal:** `go run . -i < toUniq.txt `

**Output:**

```
RAT
DOG
CAT
ESEL
HUND
```

**Uniq command:**

**Terminal:**  `uniq -i < toUniq.txt `

**Output:**

```
RAT
Dog
Cat
Esel
Hund
```


**Conclusion:**
Both results are almost equal. The only thing that is different is upper and lower case in the output.

**Review by Al2Klimov — APPROVED** [review]

**Pull request merged**
