### PR TITLE
add parameter d

### LINKED ISSUE #3: Parameter -d

### PR DESCRIPTION
**Pull request by justinmueller05082000**
fixes #3

### CODE REVIEW

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Why don't you check for EOF in all cases?

**Comment by justinmueller05082000** [comment]
Because it does not print the last line then

**Comment by Al2Klimov** [comment]
Then you have to make sure it prints the last line.

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
* [x] `git reset --soft HEAD~$(git rev-list --count $(git merge-base HEAD master)..HEAD^)`
* [x] `git commit --amend --no-edit`
* [x] `git push -f origin feature/add-parameter-d-3`

**Review by Al2Klimov — CHANGES_REQUESTED** [review]
Write a test protocol.

**Comment by justinmueller05082000** [comment]
**Test protocol:**

**toUniq.txt:**

```
Rat
Rat
Rat
Dog
Dog
Cat
Esel
Esel
Esel
Hund
Hund
```

**Go code:**

**Terminal:** `go run . -d < toUniq.txt `

**Output:**

```
Rat
Dog
Esel
Hund
```

**Uniq command:**

**Terminal:**  `uniq -d < toUniq.txt `

**Output:**

```
Rat
Dog
Esel
Hund
```


**Conclusion:**
Both results are euqal.

**Review by Al2Klimov — APPROVED** [review]

**Pull request merged**
